%% Linear Data Reconciliation
% This main function loads the true data generated by simulating the model of
% the binary distillation column. It then artificially corrupts the true
% data (using measureReal) and performs linear data reconciliation on the corrupted
% 'measurements', for both AVM & SVM. Lastly, it evaluates the effectiveness of linear DR.

% Key:
% AVM - All Variables Measured 
% SVM - Some Variables Measured
% MAPE - Mean Absolute Percentage Error

%% Initialise
clear
clc

%% Load data
load('true_data', 'MM', 'X', 'tSol', 'true_data', 'v', 'p', 'u')

%% Measurements with Variance
% The function measureReal artificially corrupts the true data
variance = linspace(0.005,5,100);

for i = 1:100
    [measured_data, time] = measureReal(MM, X, v, u, p, tSol, variance(i));

    % Measurement matrix - Matrix with all variables measured
    measurements = [measured_data.L1; measured_data.L2; measured_data.L3; measured_data.L4; measured_data.LB;...
                    measured_data.LD; measured_data.LR; measured_data.V0; measured_data.V1;...
                    measured_data.V2; measured_data.V3; measured_data.V4; measured_data.LF];

    % Variance Matrix
    W = varianceMatrix(13, variance(i));

    %    L1 L2 L3 L4 LB LD LR V0 V1 V2 V3 V4 LF
    A = [+1 +0 +0 +0 -1 +0 +0 -1 +0 +0 +0 +0 +0;...
         -1 +1 +0 +0 +0 +0 +0 +1 -1 +0 +0 +0 +0;... 
         +0 -1 +1 +0 +0 +0 +0 +0 +1 -1 +0 +0 +1;... 
         +0 +0 -1 +1 +0 +0 +0 +0 +0 +1 -1 +0 +0;... 
         +0 +0 +0 -1 +0 +0 +1 +0 +0 +0 +1 -1 +0;... 
         +0 +0 +0 +0 +0 -1 -1 +0 +0 +0 +0 +1 +0];

    % Linear DR - AVM 
    xhat = measurements - (W\A')*((A*(W\A'))\(A*measurements));
    LB_avm = xhat(5,:);

    % Error metrics
    % MAPE - Mean Absolute Percentage Error
    mapeM(i,:)    = mean(100*abs((true_data.LB(:,100:end) - measured_data.LB(:,100:end))./true_data.LB(:,100:end))); %mean((true_data.LB - measured_data.LB).^2);
    mape_avm(i,:) = mean(100*abs((true_data.LB(:,100:end) - LB_avm(:,100:end))./true_data.LB(:,100:end))); %mean((true_data.LB - LB_avm).^2);  
    mapeDiff(i,:) = mapeM(i,:) - mape_avm(i,:);
    
    % res - Residules
    resM(i,:) = true_data.LB - measured_data.LB;
    res_avm(i,:) = true_data.LB - LB_avm;


subplot(2,1,2)
patch([variance fliplr(variance)], [mapeM' fliplr(mape_avm')], 'y')
hold on
plot(variance, mapeM, 'r', variance, mape_avm, 'b')
hold off
xlabel("Variance"); ylabel("mapeValue")
legend("Diff","Measurements","DR")
title("Comparison of MAPE values between measurements and DR")

sgtitle("Plots illustrating the effect of DR with increasing variance")

